version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - uploads:/uploads
    command: [ "node", "backend.js" ]
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: [ "npm", "start" ]
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  uploads:
    name: "uploads_ml"
